def ellie():
    print ("Ellie")

def act1_scene6():
    print("The members Princess Dia, Dinh Jin Ping, Doctor Nikki, and Dracula look up to the brothers Don Quijote and Don Tour as their leaders. Don Tour, Don Quijote’s younger brother, considers himself as a power ranger. The blue one. He takes inspiration from him. He has everything to resemble him and act like him, amid his heavy drug addiction.")

def act2_scene6():
    print("In a single nigt, their peaceful lives were changed forever. Quijote, traumatized by his helplessness, craved strength above all else, in order to protect the people he loves. Tour, the younger brother, was more unlucky, unable to overcome their parents’ death. While Quijote trained, Tour strayed, hiding from the weight of loss behind false courage and the poisons that dulled his pain. Yet the tragedy of Kallin was not theirs alone. Princess Dia too had lost her parents to Git, her throne turned into a burden she could not yet bear. Dinh Jin Ping, who dreamed of traveling the land, would find no choice but to raise his hand in battle. Doctor Nikki, in his strange obsession with rebuilding broken things, saw only more shattered lives to mend. And Dracula, born of shadow, was drawn to the river of blood spilling out. Each carried scars of their own, but together, these wounds would bind them. This was the beginning of the Robaddies, forged not in glory, but in fire, grief, and the promise of vengeance against Git.")

def act3_scene6():
    print("As the moon cut through the smoke of battle, the Robaddies strongly believe in their fate to win this war. But fate doesn’t always go as they hope to do…. In an inconceivably silent moment in the war, as if it were the calm before the storm. Our heroes stood on the frontline, filled with hopes to bring this catastrophe to the end. Princess Dia stepped behind Don Quijote. For one heartbeat, he believed she stood at his side as comrade, as queen, as ally. But her dagger slid between his ribs, and his cry broke the night. Don Tour turned, screaming his brother’s name, while Dinh Jin Ping’s arrow faltered mid-flight. Doctor Nikki froze, his monstrous creations stalling, and even Dracula recoiled with a hiss. Princess Dia’s eyes burned with a grief too twisted to name. “The Git cannot be destroyed,” she whispered, “but I can survive.” Don Quijote collapsed, the hero undone by the very one he trusted most. The battlefield stilled, and in that silence, Git’s laughter echoed. The Robaddies’ fate was sealed, victory belonged not to them, but to betrayal.")
    
