def kien():
  print("Kien")

def act1_scene5():
    print("Dracul, the scaries member of the Robaddies, often scares the other members, Don Quijote, Princess Dia, Dinh Jin Ping, Doctor Nikki, and Don Tour. Dracula is a hero who hides within the shadows, wielding ancient powers as he fights alongside his teammates. His eerie presence often sends shivers through his friends and enemies.")

def act2_scene5():
    print("The attac on Kalli came like lightning in the night, sudden and merciless. Arrows rained from the heavens, homes erupted in fire, and the cries of the innocent filled the streets. The peaceful time on Kallin stood no chance, the army of the night was running all over town, chaos erupted everywhere. The chief guard, Don John, father to Quijote and Tour, can only stood still in front of his house in the hope of protecting his family. Sword drawn, he slashes down countless of enemies, in the town that is engulfed by flames. Hearing the desperate cries of the citizen, unable to contain himself Don John rushes into the hellish battle to help. Seeing her husband rush into battle, Daniela, their mom, can only rush the boys safety in the hope that they will survive. Being rushed by the unsurmountable of Git soldiers, their mother can only stay behind as bait in order for her boys to survive. This event is the major gear that forms the Robaddies party of Don Quijote, Don Tour, Princess Dia, Dinh Jin Ping, Doctor Nikki, Dracula.")

def act3_scene5():
    print("The plain outsid Jornadheim erupted into chaos as the Robaddies clashed with the Git. Don Quijote’s blade gleamed in the torchlight, cleaving through enemy ranks with fury born of a man revenging his father’s death. Don Tour fought at his side, bottle in hand, striking with the astounding courage of a man who is completely blacking out. Princess Dia unleashed her rage, her war cries echoing across the valley, while Dinh Jin Ping’s arrows whistled through the air, felling Git soldiers before they could draw breath. Doctor Nikki unleashed twisted contraptions of bone and steel, horrifying both ally and foe. Dracula, descended in his true form. Thousands of bats swarmed the battlefield, tearing through flesh and bones. Together, the Robaddies seemed unstoppable, yet the enemy was endless.")
